select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender,
sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,
purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= 
(select AVG (purchase_amount) from customer)

--Q3. Which are the top 10 products with the highest average review rating?
select item_purchased,
round(AVG(review_rating::numeric),2) as "Average Product Raing"
from customer
group by item_purchased
order by avg(review_rating) desc
Limit 10;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
Group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total 
--revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * sum(case when discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
Limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number 
--of previous purchases, and show the count of each segment.
with customer_type as (
	select 
	customer_id, 
	previous_purchases,
	case 
		when previous_purchases = 1 THEN 'New'
		when previous_purchases BETWEEN 2 AND 10 THEN 'Recurring'
		else 'Loyal'
		end as customer_segment
	from customer
)
select 
customer_segment,
count (*) as "Number of Customers"
from customer_type
group by customer_segment

--Q7.1 Refine the segmentation rules to include Recency (purchase_frequency_days) 
--with the frequency (previous_purchases), and show the count of each segment.
WITH rfm_scoring AS (
    SELECT 
        Customer_ID,
        previous_purchases,
        purchase_frequency_days,
        -- Step 1: Calculate Recency Score (Shorter days = Higher Recency)
        CASE 
            WHEN purchase_frequency_days <= 14 THEN 3
            WHEN purchase_frequency_days BETWEEN 30 AND 90 THEN 2
            WHEN purchase_frequency_days >= 360 THEN 1
            ELSE 1
        END AS r_score,
        -- Step 2: Calculate Frequency Score (Cleaned non-overlapping rules)
        CASE 
            WHEN previous_purchases > 10 THEN 3
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 2
            WHEN previous_purchases <= 1 THEN 1
            ELSE 1
        END AS f_score
    FROM customer
),
rfm_segmentation AS (
    SELECT 
        Customer_ID,
        r_score,
        f_score,
        -- Step 3: Map R and F score combinations to business segments
        CASE 
            WHEN r_score = 3 AND f_score = 3 THEN 'Champions'
            WHEN r_score = 3 AND f_score = 1 THEN 'Hot Prospects'
            WHEN r_score = 1 AND f_score = 3 THEN 'At-Risk Loyalists'
            WHEN r_score = 1 AND f_score = 1 THEN 'Hibernating'
            ELSE 'Core Regulars'
        END AS customer_segment
    FROM rfm_scoring
)
-- Step 4: Aggregate results and calculate exact proportions
SELECT 
    customer_segment,
    COUNT(Customer_ID) AS total_customers,
    ROUND(
        (COUNT(Customer_ID)::NUMERIC * 100.0) / SUM(COUNT(Customer_ID)) OVER(), 
        2
    ) AS pct_of_total
FROM rfm_segmentation
GROUP BY customer_segment
ORDER BY total_customers DESC;

-- Q7.2 Which segments drive recurring revenue? Breakdown the counts and subscription rates 
--(Subscription Status = 'Yes') across our customer segments.
WITH rfm_scoring AS (
    SELECT 
        Customer_ID, Subscription_Status,
        CASE WHEN purchase_frequency_days <= 14 THEN 3
             WHEN purchase_frequency_days BETWEEN 30 AND 90 THEN 2
             ELSE 1 END AS r_score,
        CASE WHEN previous_purchases > 10 THEN 3
             WHEN previous_purchases BETWEEN 2 AND 10 THEN 2
             ELSE 1 END AS f_score
    FROM customer
),
rfm_segmentation AS (
    SELECT *,
        CASE WHEN r_score = 3 AND f_score = 3 THEN 'Champions'
             WHEN r_score = 3 AND f_score = 1 THEN 'Hot Prospects'
             WHEN r_score = 1 AND f_score = 3 THEN 'At-Risk Loyalists'
             WHEN r_score = 1 AND f_score = 1 THEN 'Hibernating'
             ELSE 'Core Regulars' END AS customer_segment
    FROM rfm_scoring
)
SELECT 
    customer_segment,
    COUNT(Customer_ID) AS total_customers,
    COUNT(CASE WHEN Subscription_Status = 'Yes' THEN 1 END) AS active_subscribers,
    ROUND(
        (COUNT(CASE WHEN Subscription_Status = 'Yes' THEN 1 END)::NUMERIC * 100.0) / COUNT(Customer_ID), 
        2
    ) AS subscription_rate_pct
FROM rfm_segmentation
GROUP BY customer_segment
ORDER BY subscription_rate_pct DESC;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
	select
	category,
	item_purchased,
	count(customer_ID) as total_orders,
	row_number() over (partition by category order by count(customer_id) desc) as item_rank
	from customer
	group by category, item_purchased
)
select
	item_rank,
	category,
	item_purchased,
	total_orders
	from item_counts
	where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status 

--Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

--Q11. Which payment method is associated with the highest purchase amount? 
SELECT 
    Payment_Method,
    SUM(Purchase_Amount) AS total_revenue,
    COUNT(Customer_ID) AS total_transactions,
    ROUND(AVG(Purchase_Amount), 2) AS average_order_value
FROM customer
GROUP BY Payment_Method
ORDER BY total_revenue DESC
